version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"  # Accès à WordPress via http://localhost:8080
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: example
      WORDPRESS_DB_NAME: mydatabase
    volumes:
      - ./wordpress:/var/www/html  # Persistance des fichiers WordPress

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydatabase
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
  wordpress:
